FROM ubi8/ubi:8.5
MAINTAINER srinivas.gogineni@delta.com
ENV DESCRIPTION="A custom apache container based on UBI8"
LABEL description=$DESCRIPTION
RUN yum install -y httpd && \
    yum clean all && \
    echo "First container file" > /var/www/html/index.html
EXPOSE 8080
EXPOSE 8443
CMD ["httpd", "-D", "FOREGROUND"]

